### ISSUE TITLE
 ImportError: No module named formlib.formbase

### ISSUE THREAD

**Issue by richardtc** [plomino/PlominoDoc#9]
Hi,
Getting an error on trying to start Plone after installing Products.CMFPlomino==1.19.6 on Plone 5.0.2.
Cheers,
Richard
System: Linux Mint Rebecca (Ubuntu Trusty) 64

buildout.cfg:
...
eggs =
    Plone
    Pillow
    Products.PloneHotfix20151208
    quintagroup.theme.sunrain
    Products.PloneFormGen
    plone.app.theming
    Products.CMFPlomino
...

Error:
$ ./bin/plonectl fg
instance: 2016-01-24 14:11:24 INFO ZServer HTTP server started at Sun Jan 24 14:11:24 2016
	Hostname: 0.0.0.0
	Port: 8080
2016-01-24 14:11:27 INFO Products.PloneFormGen gpg_subprocess initialized, using /usr/bin/gpg
2016-01-24 14:11:27 INFO Products.PloneHotfix20151208 Applied searchFulltextForMembers patch
2016-01-24 14:11:27 INFO Products.PloneHotfix20151208 Hotfix installed
Traceback (most recent call last):
...
    ZopeXMLConfigurationError: File "/home/rcooper/Plone/buildout-cache/eggs/plone.app.widgets-2.0.2-py2.7.egg/plone/app/widgets/configure.zcml", line 14.2-14.41
    ZopeXMLConfigurationError: File "/home/rcooper/Plone/buildout-cache/eggs/Products.CMFPlone-5.0.2-py2.7.egg/Products/CMFPlone/configure.zcml", line 108.4-112.10
    ZopeXMLConfigurationError: File "/home/rcooper/Plone/buildout-cache/eggs/Products.CMFPlomino-1.19.6-py2.7.egg/Products/CMFPlomino/configure.zcml", line 17.2-17.30
    ZopeXMLConfigurationError: File "/home/rcooper/Plone/buildout-cache/eggs/Products.CMFPlomino-1.19.6-py2.7.egg/Products/CMFPlomino/fields/configure.zcml", line 22.3-26.10
    ImportError: No module named formlib.formbase

**Comment by ebrehault** [comment]
Hi,

On Plone 5, you are supposed to use Plomino 2 (it is still an alpha, but it is almost complete).

Note: you should report this kind of issue in the Plomino repository issues, not in PlominoDoc :)

**Comment by richardtc** [comment]
Thanks Eric.
Working fine now.
hmmm.  sorry, not sure how I got to PlominoDoc ...

**Comment by ebrehault** [comment]
no problem :)
